/**
 * ExportPage — Model export & evaluation summary.
 *
 * Final step of the Overflow RLHF/GRPO pipeline. Displays the trained model's
 * before/after eval metrics, architecture details, and provides download
 * buttons for model weights (mock JSON) and an eval report (text).
 */

import { useNavigate } from "react-router-dom";
import { useStore } from "../store";
import { colors, fonts, typeScale, spacing, glass, radius } from "../theme";
import {
  CheckCircle,
  Download,
  FileText,
  RotateCcw,
  ArrowUp,
  ArrowDown,
  Minus,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDate(ts: number): string {
  const d = new Date(ts);
  return d.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function ExportPage() {
  const navigate = useNavigate();
  const trainedModel = useStore((s) => s.trainedModel);
  const preferences = useStore((s) => s.preferences);
  const actions = useStore((s) => s.actions);

  // Guard — no trained model yet
  if (!trainedModel) {
    return (
      <div
        style={{
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: spacing.lg,
          background: colors.bgDeep,
          fontFamily: fonts.sans,
          color: colors.textSecondary,
        }}
      >
        <span style={{ ...typeScale.h2 }}>No trained model available</span>
        <button
          onClick={() => navigate("/")}
          style={{
            ...typeScale.body,
            fontFamily: fonts.sans,
            padding: `${spacing.sm}px ${spacing.xl}px`,
            background: colors.bgSurface,
            color: colors.textPrimary,
            border: `1px solid ${colors.border}`,
            borderRadius: radius.md,
            cursor: "pointer",
          }}
        >
          Back to Home
        </button>
      </div>
    );
  }

  // ----- Download handlers -------------------------------------------------

  const handleDownloadWeights = () => {
    const payload = {
      model: "overflow-policy-grpo",
      version: trainedModel.version,
      architecture: "transformer-12l-198m",
      format: "safetensors",
      evalMetrics: { ...trainedModel.evalMetrics },
      trainedAt: new Date(trainedModel.trainedAt).toISOString(),
      note: "Mock model \u2014 production version would contain actual weights",
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: "application/json",
    });
    downloadBlob(blob, `overflow-policy-grpo-${trainedModel.version}.json`);
  };

  const handleDownloadReport = () => {
    const lines: string[] = [
      "=".repeat(60),
      "  Overflow \u2014 GRPO Evaluation Report",
      "=".repeat(60),
      "",
      `Model:            ${trainedModel.name}`,
      `Version:          ${trainedModel.version}`,
      `Architecture:     Transformer (12L, 198M params)`,
      `Training method:  GRPO (Group Relative Policy Optimization)`,
      `Preference pairs: ${trainedModel.preferences * 3}`,
      `Training epochs:  ${trainedModel.epochs}`,
      `Total steps:      ${trainedModel.steps}`,
      `Trained at:       ${formatDate(trainedModel.trainedAt)}`,
      "",
      "-".repeat(60),
      "  Before / After Comparison",
      "-".repeat(60),
      "",
    ];

    for (const c of trainedModel.comparisons) {
      const dir = c.improved ? "(improved)" : c.after === c.before ? "(unchanged)" : "(regressed)";
      lines.push(
        `  ${c.metric.padEnd(24)} ${String(c.before).padStart(8)} ${c.unit}  ->  ${String(c.after).padStart(8)} ${c.unit}  ${dir}`,
      );
    }

    lines.push(
      "",
      "-".repeat(60),
      "  Final Eval Metrics",
      "-".repeat(60),
      "",
      `  Avg Reward:      ${trainedModel.evalMetrics.avgReward}`,
      `  Collision Rate:  ${trainedModel.evalMetrics.collisionRate}`,
      `  Avg TTC:         ${trainedModel.evalMetrics.avgTTC}`,
      `  Safety Score:    ${trainedModel.evalMetrics.safetyScore}`,
      "",
      "=".repeat(60),
      "  Generated by Overflow \u2014 RLHF/GRPO Training Platform",
      "=".repeat(60),
      "",
    );

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    downloadBlob(blob, `overflow-eval-report-${trainedModel.version}.txt`);
  };

  const handleRestart = () => {
    actions.resetPipeline();
    actions.reset();
    navigate("/");
  };

  // ----- Render helpers ----------------------------------------------------

  const preferenceCount = trainedModel.preferences;
  const pairCount = trainedModel.preferences * 3;

  return (
    <div
      style={{
        minHeight: "100vh",
        background: colors.bgDeep,
        fontFamily: fonts.sans,
        color: colors.textPrimary,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: `${spacing.xxl * 2}px ${spacing.xl}px ${spacing.xxl}px`,
        overflowY: "auto",
      }}
    >
      <div style={{ width: "100%", maxWidth: 900 }}>
        {/* ── HERO ──────────────────────────────────────────────────── */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            marginBottom: spacing.xxl * 1.5,
          }}
        >
          <div
            style={{
              width: 72,
              height: 72,
              borderRadius: "50%",
              background: "rgba(0, 232, 157, 0.12)",
              border: `2px solid ${colors.success}`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: spacing.xl,
              boxShadow: `0 0 32px rgba(0, 232, 157, 0.2)`,
            }}
          >
            <CheckCircle size={36} color={colors.success} />
          </div>

          <h1
            style={{
              ...typeScale.h1,
              fontSize: 28,
              margin: 0,
              marginBottom: spacing.sm,
              background: "linear-gradient(135deg, #E8ECF4, #00E89D)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            Model Training Complete
          </h1>

          <span
            style={{
              ...typeScale.h2,
              fontFamily: fonts.mono,
              color: colors.accent,
              marginBottom: spacing.xs,
            }}
          >
            {trainedModel.name} {trainedModel.version}
          </span>

          <span style={{ ...typeScale.body, color: colors.textSecondary }}>
            Trained on {preferenceCount} preference reviews via GRPO
          </span>
        </div>

        {/* ── BEFORE / AFTER COMPARISON TABLE ───────────────────────── */}
        <div
          style={{
            ...glass,
            padding: spacing.xl,
            marginBottom: spacing.xxl,
            border: `1px solid ${colors.borderAccent}`,
            background:
              "linear-gradient(180deg, rgba(14,17,28,0.92) 0%, rgba(10,13,22,0.96) 100%)",
          }}
        >
          <h2
            style={{
              ...typeScale.h2,
              margin: 0,
              marginBottom: spacing.xl,
              textAlign: "center",
            }}
          >
            Policy Evaluation Comparison
          </h2>

          {/* Header row */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 32px 1fr",
              gap: spacing.sm,
              padding: `${spacing.sm}px ${spacing.md}px`,
              marginBottom: spacing.sm,
            }}
          >
            <span style={{ ...typeScale.caption, color: colors.textDim }} />
            <span
              style={{
                ...typeScale.caption,
                color: colors.textDim,
                textAlign: "right",
              }}
            >
              Base Policy (v1)
            </span>
            <span />
            <span
              style={{
                ...typeScale.caption,
                color: colors.accent,
                textAlign: "right",
              }}
            >
              GRPO Policy (v2)
            </span>
          </div>

          {/* Metric rows */}
          {trainedModel.comparisons.map((c, i) => {
            const improved = c.improved;
            const unchanged = c.before === c.after;
            const rowColor = improved
              ? colors.success
              : unchanged
                ? colors.textDim
                : colors.error;

            return (
              <div
                key={c.metric}
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr 32px 1fr",
                  gap: spacing.sm,
                  padding: `${spacing.md}px ${spacing.md}px`,
                  borderRadius: radius.sm,
                  background:
                    i % 2 === 0 ? "rgba(255,255,255,0.015)" : "transparent",
                  alignItems: "center",
                }}
              >
                {/* Metric name */}
                <span
                  style={{
                    ...typeScale.body,
                    fontWeight: 500,
                    color: colors.textSecondary,
                  }}
                >
                  {c.metric}
                </span>

                {/* Before value */}
                <span
                  style={{
                    ...typeScale.mono,
                    fontSize: 13,
                    textAlign: "right",
                    color: colors.textDim,
                  }}
                >
                  {c.before} {c.unit}
                </span>

                {/* Arrow */}
                <span
                  style={{
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    color: rowColor,
                  }}
                >
                  {improved ? (
                    <ArrowUp size={14} />
                  ) : unchanged ? (
                    <Minus size={14} />
                  ) : (
                    <ArrowDown size={14} />
                  )}
                </span>

                {/* After value */}
                <span
                  style={{
                    ...typeScale.mono,
                    fontSize: 13,
                    textAlign: "right",
                    color: improved ? colors.success : unchanged ? colors.textSecondary : colors.error,
                    fontWeight: improved ? 600 : 400,
                    textShadow: improved
                      ? `0 0 8px rgba(0, 232, 157, 0.35)`
                      : "none",
                  }}
                >
                  {c.after} {c.unit}
                </span>
              </div>
            );
          })}
        </div>

        {/* ── MODEL DETAILS CARD ────────────────────────────────────── */}
        <div
          style={{
            ...glass,
            padding: spacing.xl,
            marginBottom: spacing.xxl,
          }}
        >
          <h2
            style={{
              ...typeScale.h3,
              margin: 0,
              marginBottom: spacing.lg,
              color: colors.textSecondary,
            }}
          >
            Model Details
          </h2>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              gap: `${spacing.md}px ${spacing.xxl}px`,
            }}
          >
            {(
              [
                ["Model", "overflow-policy-grpo"],
                ["Architecture", "Transformer (12L, 198M params)"],
                ["Training method", "GRPO (Group Relative Policy Optimization)"],
                ["Preference pairs", String(pairCount)],
                ["Training epochs", String(trainedModel.epochs)],
                ["Total steps", String(trainedModel.steps)],
                ["Trained at", formatDate(trainedModel.trainedAt)],
              ] as [string, string][]
            ).map(([label, value]) => (
              <div key={label} style={{ display: "flex", flexDirection: "column", gap: 2 }}>
                <span style={{ ...typeScale.caption, color: colors.textDim }}>
                  {label}
                </span>
                <span
                  style={{
                    ...typeScale.mono,
                    fontSize: 12,
                    color: colors.textPrimary,
                  }}
                >
                  {value}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* ── EXPORT BUTTONS ────────────────────────────────────────── */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: spacing.lg,
            marginBottom: spacing.xxl * 1.5,
          }}
        >
          {/* Download Model Weights */}
          <button
            onClick={handleDownloadWeights}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: spacing.sm,
              padding: `${spacing.lg}px ${spacing.xl}px`,
              background: `linear-gradient(135deg, ${colors.accent}, ${colors.accentBlue})`,
              color: colors.bgDeep,
              fontFamily: fonts.sans,
              fontWeight: 600,
              fontSize: 14,
              border: "none",
              borderRadius: radius.md,
              cursor: "pointer",
              transition: "opacity 0.15s",
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.opacity = "0.88";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.opacity = "1";
            }}
          >
            <Download size={18} />
            Download Model Weights
          </button>

          {/* Download Eval Report */}
          <button
            onClick={handleDownloadReport}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: spacing.sm,
              padding: `${spacing.lg}px ${spacing.xl}px`,
              background: colors.bgSurface,
              color: colors.textPrimary,
              fontFamily: fonts.sans,
              fontWeight: 600,
              fontSize: 14,
              border: `1px solid ${colors.border}`,
              borderRadius: radius.md,
              cursor: "pointer",
              transition: "all 0.15s",
            }}
            onMouseEnter={(e) => {
              const btn = e.currentTarget as HTMLButtonElement;
              btn.style.borderColor = colors.accent;
              btn.style.color = colors.accent;
            }}
            onMouseLeave={(e) => {
              const btn = e.currentTarget as HTMLButtonElement;
              btn.style.borderColor = colors.border;
              btn.style.color = colors.textPrimary;
            }}
          >
            <FileText size={18} />
            Download Eval Report
          </button>
        </div>

        {/* ── START NEW SESSION ──────────────────────────────────────── */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: spacing.xl,
            paddingBottom: spacing.xxl,
          }}
        >
          <button
            onClick={handleRestart}
            style={{
              display: "flex",
              alignItems: "center",
              gap: spacing.sm,
              padding: `${spacing.sm}px ${spacing.xl}px`,
              background: "transparent",
              color: colors.textSecondary,
              fontFamily: fonts.sans,
              fontWeight: 500,
              fontSize: 13,
              border: `1px solid ${colors.borderSubtle}`,
              borderRadius: radius.pill,
              cursor: "pointer",
              transition: "all 0.15s",
            }}
            onMouseEnter={(e) => {
              const btn = e.currentTarget as HTMLButtonElement;
              btn.style.borderColor = colors.border;
              btn.style.color = colors.textPrimary;
            }}
            onMouseLeave={(e) => {
              const btn = e.currentTarget as HTMLButtonElement;
              btn.style.borderColor = colors.borderSubtle;
              btn.style.color = colors.textSecondary;
            }}
          >
            <RotateCcw size={14} />
            Start New Session
          </button>

          <span
            style={{
              ...typeScale.small,
              color: colors.textMuted,
              textAlign: "center",
            }}
          >
            Overflow &mdash; RLHF/GRPO Training Platform for Autonomous Driving
          </span>
        </div>
      </div>
    </div>
  );
}
